Repository ingame-app/ingame, pull requests merged in 2024-05, with the labels that each got.

#29 [FE] 공통 컴포넌트 개발 (1)
  client/package-lock.json
  client/package.json
  client/src/components/Button.tsx
  client/src/components/Dropdown.tsx
  client/src/components/InputBox.tsx
  client/src/components/Top.tsx
  client/src/constant/route.ts
  client/src/hooks/useOutsideClick.ts
  client/src/layout/Layout.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Test.tsx
  client/src/routes/routing.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: ✨ Feat, 🎨 Html&Css, 🖥️FE

#32 [FE] Model 파일 생성, Interface 설정
  client/src/layout/Layout.tsx
  client/src/models/profilePhoto.model.ts
  client/src/models/quest.model.ts
  client/src/models/sideQuest.model.ts
  client/src/models/user.model.ts
  client/src/models/userInfo.model.ts
Labels: ✨ Feat, 🖥️FE

#27 [BE] 사용자 API 기능 1차 구현 완료
  server/package-lock.json
  server/package.json
  server/src/apis/users/dto/create-user.dto.ts
  server/src/apis/users/dto/update-user.dto.ts
  server/src/apis/users/dto/user-response.dto.ts
  server/src/apis/users/entities/profile-photo.entity.ts
  server/src/apis/users/entities/user-info.entity.ts
  server/src/apis/users/entities/user.entity.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.module.ts
  server/src/apis/users/users.service.ts
Labels: ✨ Feat, 📱BE

#38 [BE]Auth API 기능 구현과 Users API 수정 및 기능 추가 완료
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/apis/auth/auth.controller.ts
  server/src/apis/auth/auth.guard.ts
  server/src/apis/auth/auth.module.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/auth/dto/create-auth.dto.ts
  server/src/apis/auth/dto/jwt-payload.dto.ts
  server/src/apis/auth/dto/login-user.dto.ts
  server/src/apis/auth/dto/update-auth.dto.ts
  server/src/apis/users/dto/profile-photo.dto.ts
  server/src/apis/users/dto/update-user.dto.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.module.ts
  server/src/apis/users/users.service.ts
  server/src/commons/decorators/auth.decorator.ts
  server/src/config/jwt.config.ts
Labels: ✨ Feat, 🔨 Refactor, 📱BE

#39 [FE] React-query 사용과 랭킹 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/ranking.api.ts
  client/src/assets/images/Profile-PNG-File.png
  client/src/assets/images/tropy.png
  client/src/components/CloseButton.tsx
  client/src/components/Hamberger.tsx
  client/src/components/RankingCard.tsx
  client/src/components/RankingCardList.tsx
  client/src/components/modals/Profile.tsx
  client/src/constant/api.ts
  client/src/constant/route.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockRanking.ts
  client/src/mocks/handlers/auth.ts
  client/src/mocks/handlers/ranking.ts
  client/src/models/ranking.model.ts
  client/src/pages/Main.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Ranking.tsx
  client/src/provider/queryProvider.tsx
  client/src/routes/routing.tsx
  client/src/shared/dummy.ts
Labels: ✨ Feat, 🎨 Html&Css, 🖥️FE

#36 [FE] 로그인, 회원가입 페이지 개발
  client/src/api/auth.api.ts
  client/src/api/auth.ts
  client/src/api/users.api.ts
  client/src/components/InputBox.tsx
  client/src/components/NavigationText.tsx
  client/src/components/Title.tsx
  client/src/components/Top.tsx
  client/src/constant/api.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useUser.ts
  client/src/layout/Layout.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers/auth.ts
  client/src/mocks/handlers/users.ts
  client/src/pages/Login.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/Test.tsx
  client/src/pages/counter.tsx
  client/src/store/authSlice.ts
  client/src/store/counterSlice.ts
  client/src/store/index.ts
Labels: ✨ Feat, 🎨 Html&Css, 🖥️FE

#42 [FE] Redux-persist 설정
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/src/pages/Main.tsx
  client/src/pages/MainPage.tsx
  client/src/store/index.ts
Labels: ✨ Feat, 🖥️FE, ⚙️ conf

#46 [BE] 랭킹 조회 및 회원가입 수정 완료
  server/src/apis/ranking/dto/create-ranking.dto.ts
  server/src/apis/ranking/dto/ranking-response.dto.ts
  server/src/apis/ranking/dto/update-ranking.dto.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.module.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/users.service.ts
Labels: ✨ Feat, 🐞 BugFix, 📱BE

#48 [FE] 드롭다운 기능 추가 개발 및 랭킹 페이지 너비 수정
  client/src/api/auth.api.ts
  client/src/components/Dropdown.tsx
  client/src/components/Hamberger.tsx
  client/src/components/RankingCard.tsx
  client/src/components/RankingCardList.tsx
  client/src/constant/api.ts
  client/src/hooks/useAuth.ts
  client/src/mocks/browser.ts
  client/src/mocks/handlers/auth.ts
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/Ranking.tsx
  client/src/pages/Test.tsx
  client/src/store/authSlice.ts
  client/src/utils/axios.ts
  client/src/utils/tokenUtils.ts
Labels: ✨ Feat, 🎨 Html&Css, 🖥️FE

#52 메인페이지의 ProfilieSection 마크업 및 progress Bar 구현
  client/package-lock.json
  client/package.json
  client/src/api/ranking.api.ts
  client/src/api/users.api.ts
  client/src/assets/images/edit.png
  client/src/components/EditProfileButton.tsx
  client/src/components/ProgressBar.tsx
  client/src/components/UserProfile.tsx
  client/src/constant/api.ts
  client/src/constant/queryKey.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockUser.ts
  client/src/mocks/handlers/users.ts
  client/src/models/user.model.ts
  client/src/models/userInfo.model.ts
  client/src/pages/Main.tsx
Labels: 🖥️FE

#50 [FE] Profile Modal 생성
  client/src/api/ranking.api.ts
  client/src/api/users.api.ts
  client/src/components/CloseButton.tsx
  client/src/components/Modal.tsx
  client/src/components/ProfileIntroInputBox.tsx
  client/src/components/QuestInputBox.tsx
  client/src/components/modals/Profile.tsx
  client/src/constant/api.ts
  client/src/layout/Layout.tsx
  client/src/models/user.model.ts
  client/src/pages/Main.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: ✨ Feat, 🖥️FE

#49 [BE] TypeORM Migration 적용
  server/package-lock.json
  server/package.json
  server/src/config/datasource.config.ts
Labels: ✨ Feat, 📱BE, ⚙️ conf

#53 프로필 수정 모달 레이아웃 수정
  client/src/api/users.api.ts
  client/src/components/EditProfileButton.tsx
  client/src/components/Modal.tsx
  client/src/components/ProfileIntroInputBox.tsx
  client/src/components/QuestInputBox.tsx
  client/src/components/UserProfile.tsx
  client/src/components/modals/Profile.tsx
  client/src/components/modals/ProfileModal.tsx
Labels: 🖥️FE

#55 [FE] 메인화면 주간 캘린더 개발
  client/src/components/Hamberger.tsx
  client/src/components/WeekCalander.tsx
  client/src/constant/route.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useWeek.ts
  client/src/mocks/handlers/auth.ts
  client/src/pages/Main.tsx
  client/src/pages/Test.tsx
  client/src/routes/routing.tsx
  client/src/store/index.ts
Labels: ✨ Feat, 🎨 Html&Css, 🔨 Refactor, 🖥️FE

#56 [FE] 프로필 모달 기능 구현
  client/src/api/auth.api.ts
  client/src/api/users.api.ts
  client/src/components/CloseButton.tsx
  client/src/components/EditProfileButton.tsx
  client/src/components/QuestInputBox.tsx
  client/src/components/UserProfile.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/constant/api.ts
  client/src/constant/queryKey.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockUser.ts
  client/src/mocks/handlers/users.ts
Labels: ✨ Feat, 🖥️FE

#62 [BE] Swagger, Winston 환경 설정 및 Filter 적용 완료
  server/package-lock.json
  server/package.json
  server/src/apis/auth/auth.module.ts
  server/src/apis/users/users.controller.ts
  server/src/app.module.ts
  server/src/common/config/datasource.config.ts
  server/src/common/config/jwt.config.ts
  server/src/common/config/swagger.config.ts
  server/src/common/config/typeorm.config.ts
  server/src/common/decorators/auth.decorator.ts
  server/src/common/filters/all-exception.filter.ts
  server/src/common/logger/winston-logger.module.ts
  server/src/common/logger/winston-logger.service.ts
  server/src/common/middleware/winston-logger.middleware.ts
  server/src/main.ts
Labels: 📱BE, ⚙️ conf

#58 [BE] 메인 퀘스트 API 기능 구현
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/create-side-quest.dto.ts
  server/src/apis/quests/dto/update-side-quest.dto.ts
  server/src/apis/quests/entities/quest.entity.ts
  server/src/apis/quests/entities/side-quest.entity.ts
  server/src/apis/quests/enums/quest.enum.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
Labels: ✨ Feat, 📱BE

#63 [BE] 서브 퀘스트 API 기능 구현
  server/src/apis/quests/quests.controller.ts
Labels: ✨ Feat, 📱BE

#65 [BE] [긴급] 서브 퀘스트 API 기능 구현
  server/src/apis/quests/quests.module.ts
  server/src/apis/quests/quests.service.ts
Labels: 🐞 BugFix, 📱BE

#66 [BE] 유효성 검사와 Swagger 문서 적용 완료
  server/package.json
  server/src/apis/auth/auth.controller.ts
  server/src/apis/auth/auth.guard.ts
  server/src/apis/auth/auth.interface.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/auth/dto/login-user.dto.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/ranking/dto/ranking-response.dto.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/dto/create-user.dto.ts
  server/src/apis/users/dto/profile-photo.dto.ts
  server/src/apis/users/dto/update-user.dto.ts
  server/src/apis/users/dto/user-response.dto.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.service.ts
  server/src/common/config/swagger.config.ts
  server/src/common/filters/all-exception.filter.ts
  server/src/main.ts
Labels: ✨ Feat, 📱BE

#68 [BE] User API 수정 완료
  server/src/apis/ranking/dto/ranking-response.dto.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/dto/user-profile.dto.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.service.ts
Labels: ✨ Feat, 🐞 BugFix, 📱BE

#70 [BE] 사이드 퀘스트 API 구현
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/create-side-quest.dto.ts
  server/src/apis/quests/dto/update-side-quest.dto.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
Labels: ✨ Feat, 📱BE

#71 [BE] 퀘스트 API 컨트롤러 JwtPayloadDto에서 JwtPayload 인터페이스로 변경
  server/src/apis/quests/quests.controller.ts
Labels: 🐞 BugFix, 📱BE

#69 [FE] CreateMainQuest, EditMainQuest 페이지 구현
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/api/quest.api.ts
  client/src/components/MainBox.tsx
  client/src/components/ProfileIntroInputBox.tsx
  client/src/components/QuestInputBox.tsx
  client/src/components/SideBox.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/constant/api.ts
  client/src/constant/route.ts
  client/src/mocks/browser.ts
  client/src/mocks/handlers/quest.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Main.tsx
  client/src/pages/Test.tsx
  client/src/routes/routing.tsx
Labels: ✨ Feat, 🎨 Html&Css, 🖥️FE

#72 [FE] 주간 캘린더 및 서브 퀘스트 조회
  client/src/api/quests.api.ts
  client/src/components/CloseButton.tsx
  client/src/components/EditSubQuestButton.tsx
  client/src/components/Loading.tsx
  client/src/components/SubBox.tsx
  client/src/components/WeekCalendar.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/constant/api.ts
  client/src/constant/queryString.ts
  client/src/hooks/useMessage.ts
  client/src/hooks/useQuest.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockSubQuest.ts
  client/src/mocks/handlers/quests.ts
  client/src/models/quest.model.ts
  client/src/pages/Main.tsx
  client/src/pages/Test.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/formatter.ts
Labels: ✨ Feat, 🎨 Html&Css, 📬 API, 🖥️FE

#74 [FE] bugfix: hidden data 값 수정 TRUE or FALSE
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
Labels: 🐞 BugFix, 🖥️FE

#77 [FE] quest.api,quests.api 파일 병합 및 구조 통일
  client/src/api/quest.api.ts
  client/src/api/quests.api.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockMainQuest.ts
  client/src/mocks/handlers/auth.ts
  client/src/mocks/handlers/quest.ts
  client/src/mocks/handlers/quests.ts
  client/src/mocks/handlers/ranking.ts
  client/src/mocks/handlers/users.ts
  client/src/models/quest.model.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
Labels: Chore, 🖥️FE

#78 [FE] 로그인, 회원가입 유효성 추가 및 회원탈퇴 기능 추가
  client/src/api/users.api.ts
  client/src/components/Dropdown.tsx
  client/src/constant/api.ts
  client/src/constant/queryKey.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useUser.ts
  client/src/mocks/handlers/users.ts
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/SignUp.tsx
Labels: ✨ Feat, 🐞 BugFix, 🔨 Refactor, 📬 API, 🖥️FE

#81 [BE] 퀘스트 API에서 Token 불러오지 못하는 증상 및 기타 버그 수정
  server/package.json
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/create-side-quest.dto.ts
  server/src/apis/quests/dto/update-side-quest.dto.ts
  server/src/apis/quests/entities/quest.entity.ts
  server/src/apis/quests/entities/side-quest.entity.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
  server/src/common/config/datasource.config.ts
Labels: ✨ Feat, 🐞 BugFix, 📱BE

#83 [FE] login Provider 구현
  client/src/provider/loginProvider.tsx
  client/src/routes/routing.tsx
Labels: 🖥️FE

#89 [FE] CreateMainQuest,EditMainQuest페이지 기능 hooks로 분리
  client/src/hooks/useCreateQuest.ts
  client/src/hooks/useEditQuest.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
Labels: Chore, 🖥️FE

#91 [FE] 프로필 이미지 변경 기능 구현
  client/src/api/users.api.ts
  client/src/assets/images/avatar.png
  client/src/assets/images/camera.svg
  client/src/assets/images/cat.png
  client/src/assets/images/lion.png
  client/src/assets/images/rabbit.png
  client/src/assets/images/tiger.png
  client/src/assets/index.ts
  client/src/components/UserProfile/ProfileImageSection/ProfileImageSection.tsx
  client/src/components/UserProfile/UserProfile.tsx
  client/src/components/modals/ChangeProfileImageModal/ChangeProfileImageModal.tsx
  client/src/components/modals/ChangeProfileImageModal/ImageBadge/ImageBadge.tsx
  client/src/constant/api.ts
  client/src/hooks/useProfile.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockUser.ts
  client/src/mocks/handlers/users.ts
  client/src/models/profilePhoto.model.ts
  client/src/models/user.model.ts
  client/src/pages/Main.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🖥️FE

#86 [BE] 서브 퀘스트 조회 시 날짜가 하루 밀리는 오류 해결
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
Labels: 🐞 BugFix, 📱BE

#92 [FE] 서브퀘스트 이벤트 버블링 수정
  client/src/api/quests.api.ts
  client/src/components/EditSubQuestButton.tsx
  client/src/components/SubBox.tsx
  client/src/components/UserProfile/ProfileImageSection/ProfileImageSection.tsx
  client/src/hooks/useQuest.ts
  client/src/models/quest.model.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🐞 BugFix, 🎨 Html&Css, 🖥️FE

#93 [FE] 버그 수정 userIntro에 초기값이 null을 받았을 때의 오류 해결
  client/src/components/EditProfileButton.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/hooks/useEditQuest.ts
  client/src/models/user.model.ts
  client/src/models/userInfo.model.ts
Labels: 🐞 BugFix, 🖥️FE

#95 [FE] 서브 퀘스트 상태값 변경
  client/src/api/quests.api.ts
  client/src/components/SubBox.tsx
  client/src/hooks/useQuest.ts
Labels: ✨ Feat, 🖥️FE

#102 [BE] 퀘스트 API Swagger 문서 추가
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/create-side-quest.dto.ts
  server/src/apis/quests/quests.controller.ts
Labels: 📃 Docs, 📱BE

#105 [BE] 정보 조회 및 랭킹 조회 시 응답 데이터에 레벨 추가 완료
  server/src/apis/ranking/dto/ranking-response.dto.ts
  server/src/apis/ranking/ranking.module.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/dto/user-profile.dto.ts
  server/src/apis/users/users.module.ts
  server/src/apis/users/users.service.ts
  server/src/app.module.ts
  server/src/common/level-calculator/level-calculator.module.ts
  server/src/common/level-calculator/level-calculator.service.ts
  server/src/common/level-calculator/level-info.interface.ts
Labels: ✨ Feat, 📱BE

#107 [FE] 메인페이지에 메인퀘스트 컴포넌트 결합
  client/src/api/quests.api.ts
  client/src/components/CreateMainQuestButton.tsx
  client/src/components/MainBox.tsx
  client/src/components/RankingCard.tsx
  client/src/components/SideBox.tsx
  client/src/components/UserProfile/UserProfile.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/constant/api.ts
  client/src/constant/route.ts
  client/src/hooks/useCreateQuest.ts
  client/src/hooks/useEditQuest.ts
  client/src/hooks/useMainQuest.ts
  client/src/mocks/browser.ts
  client/src/mocks/data/mockMainQuest.ts
  client/src/mocks/data/mockRanking.ts
  client/src/mocks/handlers/quests.ts
  client/src/models/quest.model.ts
  client/src/models/ranking.model.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Main.tsx
Labels: ✨ Feat, 🖥️FE

#110 [FE] 에러페이지 마크업 및 navigate 기능 구현
  client/src/pages/Error.tsx
Labels: 🖥️FE

#114 [FE] useRank hook 생성 및 분리
  client/src/api/quests.api.ts
  client/src/components/RankingCardList.tsx
  client/src/components/SubBox.tsx
  client/src/components/modals/CreateSubQuestModal.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/constant/queryKey.ts
  client/src/hooks/useRank.ts
  client/src/hooks/useSubQuest.ts
  client/src/pages/Main.tsx
Labels: 🔨 Refactor, 🖥️FE

#115 [FE] Type 바꾸면서 수정해야 하는 코드들 수정
  client/src/hooks/useEditQuest.ts
  client/src/pages/EditMainQuest.tsx
Labels: 🐞 BugFix, 🖥️FE

#116 [BE] 메인 퀘스트 개별 수정 시 사이드 퀘스트 수정이 가능하도록 변경 및 일부 코드 수정
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/create-side-quest.dto.ts
  server/src/apis/quests/entities/quest.entity.ts
  server/src/apis/quests/entities/side-quest.entity.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.module.ts
  server/src/apis/quests/quests.service.ts
Labels: 🐞 BugFix, 📱BE

#118 [FE] 메인퀘스트 생성 및 수정 데이터 연결, hooks 통합
  client/src/api/quests.api.ts
  client/src/api/ranking.api.ts
  client/src/components/MainBox.tsx
  client/src/components/RankingCard.tsx
  client/src/components/RankingCardList.tsx
  client/src/components/UserProfile/UserProfile.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/constant/queryKey.ts
  client/src/hooks/useCreateQuest.ts
  client/src/hooks/useEditQuest.ts
  client/src/hooks/useMainQuest.ts
  client/src/mocks/data/mockUser.ts
  client/src/models/quest.model.ts
  client/src/models/userInfo.model.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
Labels: ✨ Feat, Chore, 🖥️FE

#117 [BE] 포인트 추가 및 감소 기능 구현 완료
  server/src/apis/point/dto/update-point.dto.ts
  server/src/apis/point/point.controller.ts
  server/src/apis/point/point.module.ts
  server/src/apis/point/point.service.ts
  server/src/apis/quests/enums/quest.enum.ts
  server/src/apis/quests/quests.service.ts
  server/src/app.module.ts
Labels: ✨ Feat, 📱BE

#119 [BE] 변수명 알아보기 쉽게 변경
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/quests.service.ts
Labels: 🔨 Refactor, 📱BE

#122 [FE] 전체적인 ui ux 수정
  client/src/components/Button.tsx
  client/src/components/Dropdown.tsx
  client/src/components/InputBox.tsx
  client/src/components/MainBox.tsx
  client/src/components/SubBox.tsx
  client/src/components/Top.tsx
  client/src/components/WeekCalendar.tsx
  client/src/components/modals/ChangeProfileImageModal/ChangeProfileImageModal.tsx
  client/src/components/modals/CreateSubQuestModal.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/hooks/useAuth.ts
  client/src/hooks/useMainQuest.ts
  client/src/hooks/useSubQuest.ts
  client/src/layout/Layout.tsx
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Main.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/formatter.ts
Labels: 📃 Docs, 🎨 Html&Css, 🖥️FE

#123 [FE] 메인퀘스트 기능과 스타일링 구현
  client/src/api/quests.api.ts
  client/src/components/MainBox.tsx
  client/src/hooks/useMainQuest.ts
  client/src/pages/EditMainQuest.tsx
  client/src/styles/globalstyles.ts
Labels: ✨ Feat, Chore, 🖥️FE

#106 [BE] 스케줄러 작성 및 모듈 적용
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/scheduler/scheduler.module.ts
  server/src/common/scheduler/scheduler.service.ts
Labels: ✨ Feat, 📱BE

#125 [BE] 퀘스트 API 버그 수정
  server/src/apis/quests/entities/quest.entity.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
Labels: 🐞 BugFix, 🔨 Refactor, 📱BE

#127 [FE] 닉네임이 길어질 시, 줄임표로 표현되도록 스타일 수정
  client/src/components/UserProfile/UserProfile.tsx
Labels: 🐞 BugFix, 🖥️FE

#126 [FE] 퀘스트 수정 페이지 : 버튼 스타일링, 데이터 추가
  client/src/api/ranking.api.ts
  client/src/components/Button.tsx
  client/src/components/MainBox.tsx
  client/src/components/RankingCard.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/hooks/useRank.ts
  client/src/mocks/data/mockRanking.ts
  client/src/mocks/handlers/ranking.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
Labels: ✨ Feat, Chore, 🖥️FE

#129 [BE] refresh token 기능 구현 완료
  server/package-lock.json
  server/package.json
  server/src/apis/auth/auth.controller.ts
  server/src/apis/auth/auth.guard.ts
  server/src/apis/auth/auth.interface.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/point/point.controller.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/users/users.controller.ts
  server/src/app.module.ts
  server/src/common/config/jwt.config.ts
  server/src/common/config/redis.config.ts
  server/src/common/filters/all-exception.filter.ts
Labels: ✨ Feat, 📱BE

#132 [BE] winston 로깅 데이터 cloudWatch로 모니터링 기능 구현 완료
  .github/workflows/backend-cd.yml
  k8s/ingame-be.tmpl
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/logger/winston-logger.service.ts
  server/src/main.ts
Labels: 📱BE, ⚙️ conf

#133 [FE] 랭킹페이지 무한스크롤, 메인화면의 사이드퀘스트 값 버그 수정
  client/src/api/quests.api.ts
  client/src/api/ranking.api.ts
  client/src/components/Button.tsx
  client/src/components/MainBox.tsx
  client/src/components/SideBox.tsx
  client/src/hooks/useMainQuest.ts
  client/src/hooks/useRank.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Ranking.tsx
Labels: 🐞 BugFix, 🖥️FE

#134 [FE] 전체 스타일링 및 리프레쉬 토큰 적용
  client/public/favicon.ico
  client/public/icons/favicon.ico
  client/public/icons/logo192.png
  client/public/icons/logo512.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/styles.css
  client/src/api/auth.api.ts
  client/src/constant/api.ts
  client/src/layout/Layout.tsx
  client/src/utils/axios.ts
Labels: ✨ Feat, 🎨 Html&Css, 📬 API, 🖥️FE

#141 [BE] Redis health 체크 기능 구현
  .github/workflows/backend-cd.yml
  .github/workflows/frontend-cd.yml
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/health/health.controller.ts
  server/src/common/health/health.module.ts
Labels: ✨ Feat, 📱BE

#148 [FE] 퀘스트 상태값 변경 end point 변경
  client/src/api/quests.api.ts
  client/src/constant/api.ts
Labels: 🐞 BugFix

#150 [BE] 퀘스트 상태 변경 시도 시 변경되지 않는 버그 수정
  server/src/apis/quests/quests.service.ts
Labels: 🐞 BugFix, 📱BE

#147 [BE] 메인 퀘스트 개별 조회 기능 추가
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
Labels: ✨ Feat, 📱BE

#155 [FE] 메인페이지에서 메인퀘스트 수정페이지로 넘어갈 때 바뀐 데이터가 반영되지않는 오류 해결
  client/src/api/quests.api.ts
  client/src/components/MainBox.tsx
  client/src/pages/EditMainQuest.tsx
Labels: 🐞 BugFix, 🖥️FE

#154 [BE] 배포 서버 Redis 연결 오류 해결 및 Pagination 구현 완료
  server/src/apis/auth/auth.module.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/ranking/dto/pagination-request.dto.ts
  server/src/apis/ranking/dto/pagination-response.dto.ts
  server/src/apis/ranking/dto/user-ranking-by-page.dto.ts
  server/src/apis/ranking/dto/user-ranking.dto.ts
  server/src/apis/ranking/ranking.controller.spec.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/users.service.ts
  server/src/app.module.ts
  server/src/common/config/redis.config.ts
  server/src/common/health/health.controller.ts
  server/src/common/health/health.module.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.provider.ts
Labels: ✨ Feat, 🐞 BugFix, 📱BE

#159 Readme 파일 수정
  README.md
Labels: 📃 Docs

#160 release 1.1.1
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  client/src/api/quests.api.ts
  client/src/components/MainBox.tsx
  client/src/pages/EditMainQuest.tsx
  server/src/apis/auth/auth.module.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.service.ts
  server/src/apis/ranking/dto/pagination-request.dto.ts
  server/src/apis/ranking/dto/pagination-response.dto.ts
  server/src/apis/ranking/dto/user-ranking-by-page.dto.ts
  server/src/apis/ranking/dto/user-ranking.dto.ts
  server/src/apis/ranking/ranking.controller.spec.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/users.service.ts
  server/src/app.module.ts
  server/src/common/config/redis.config.ts
  server/src/common/health/health.controller.ts
  server/src/common/health/health.module.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.provider.ts
Labels: 🌏 Deploy

#161 [FE] 서브퀘스트 삭제 추가
  client/src/api/quests.api.ts
  client/src/components/CloseButton.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/hooks/useSubQuest.ts
Labels: ✨ Feat, 📬 API, 🖥️FE

#163 [FE] 토큰 값 유무로 refresh token 요청 분기처리
  client/src/utils/axios.ts
Labels: 🐞 BugFix, 📬 API, 🖥️FE

#157 [FE] 메인퀘스트 날짜대로 표시 기능 추가 및 메인퀘스트 수정페이지 오류해결
  client/src/api/quests.api.ts
  client/src/components/MainBox.tsx
  client/src/components/WeekCalendar.tsx
  client/src/hooks/useMainQuest.ts
  client/src/hooks/useSubQuest.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Main.tsx
Labels: ✨ Feat, 🖥️FE

#164 release 1.1.2
  client/src/api/quests.api.ts
  client/src/components/CloseButton.tsx
  client/src/components/MainBox.tsx
  client/src/components/WeekCalendar.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/hooks/useMainQuest.ts
  client/src/hooks/useSubQuest.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Main.tsx
  client/src/utils/axios.ts
Labels: 🌏 Deploy

#166 [FE] 랭킹 무한스크롤 기능 구현 및 수정페이지 오류해결
  client/src/api/ranking.api.ts
  client/src/components/MainBox.tsx
  client/src/components/RankingCardList.tsx
  client/src/hooks/useRank.ts
  client/src/models/ranking.model.ts
  client/src/pages/Main.tsx
  client/src/pages/Ranking.tsx
Labels: ✨ Feat, 🖥️FE

#167 release 1.1.3
  client/public/manifest.json
  client/src/api/ranking.api.ts
  client/src/components/MainBox.tsx
  client/src/components/RankingCardList.tsx
  client/src/hooks/useRank.ts
  client/src/models/ranking.model.ts
  client/src/pages/Main.tsx
  client/src/pages/Ranking.tsx
Labels: 🌏 Deploy

#168 [FE] 상태 변경 메시지 오류 수정
  client/src/components/MainBox.tsx
  client/src/components/SubBox.tsx
Labels: 🐞 BugFix, 🖥️FE

#174 [FE] styles.css를 globalstyles.ts로 합치기
  client/public/index.html
  client/public/styles.css
  client/src/styles/globalstyles.ts
Labels: 🎨 Html&Css, 🖥️FE
