Repository ingame-app/ingame, pull requests merged in 2024-06, with the labels that each got.

#178 [FE] 퀘스트 생성 버튼 합치기
  client/src/components/CreateMainQuestButton.tsx
  client/src/components/CreateQuestButton.tsx
  client/src/components/CreateSubQuestButton.tsx
  client/src/components/WeekCalendar.tsx
  client/src/pages/Main.tsx
Labels: 🔨 Refactor, 🖥️FE

#177 [FE] 퀘스트 생성/수정 페이지 기능 hooks로 뺴기
  client/src/components/UserProfile/EditProfileButton.tsx
  client/src/components/UserProfile/ProfileIntroInputBox.tsx
  client/src/components/UserProfile/ProgressBar.tsx
  client/src/components/UserProfile/UserProfile.tsx
  client/src/components/common/Button.spec.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/CloseButton.tsx
  client/src/components/common/Dropdown.tsx
  client/src/components/common/InputBox.tsx
  client/src/components/common/Loading.tsx
  client/src/components/common/NavigationText.tsx
  client/src/components/common/Title.tsx
  client/src/components/common/Top.tsx
  client/src/components/common/WeekCalendar.tsx
  client/src/components/modals/ChangeProfileImageModal/ChangeProfileImageModal.tsx
  client/src/components/modals/CreateSubQuestModal.tsx
  client/src/components/modals/ProfileModal.tsx
  client/src/components/modals/SubQuestModal.tsx
  client/src/components/quests/CreateMainQuestButton.tsx
  client/src/components/quests/CreateSubQuestButton.tsx
  client/src/components/quests/MainBox.tsx
  client/src/components/quests/QuestInputBox.tsx
  client/src/components/quests/SideBox.tsx
  client/src/components/quests/SubBox.tsx
  client/src/components/ranking/RankingCard.tsx
  client/src/components/ranking/RankingCardList.tsx
  client/src/hooks/useMainQuest.ts
  client/src/pages/CreateMainQuest.tsx
  client/src/pages/EditMainQuest.tsx
  client/src/pages/Error.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/Ranking.tsx
  client/src/pages/SignUp.tsx
  client/tsconfig.json
Labels: 🔨 Refactor, 🖥️FE

#181 [FE] useWeek hook JS util화
  client/src/components/common/WeekCalendar.tsx
  client/src/hooks/useWeek.ts
  client/src/utils/weekUtils.ts
Labels: 🔨 Refactor, 🖥️FE

#182 [FE] 퀘스트완료 시 새로고침 하지않으면 경험치가 올라가지 않는 버그 수정
  client/src/components/UserProfile/UserProfile.tsx
  client/src/components/quests/MainBox.tsx
  client/src/hooks/useMainQuest.ts
  client/src/pages/Main.tsx
Labels: 🐞 BugFix, 🖥️FE

#183 [BE] oauth 기능 구현 및 transaction 수정 완료
  server/package-lock.json
  server/package.json
  server/src/apis/auth/auth.guard.ts
  server/src/apis/auth/auth.interface.ts
  server/src/apis/auth/auth.module.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/auth/controllers/auth.controller.ts
  server/src/apis/auth/controllers/oauth.controller.ts
  server/src/apis/auth/guards/google-auth.guard.ts
  server/src/apis/auth/guards/jwt-auth.guard.ts
  server/src/apis/auth/guards/local-auth.guard.ts
  server/src/apis/auth/strategies/google.strategy.ts
  server/src/apis/auth/strategies/jwt.strategy.ts
  server/src/apis/auth/strategies/local.strategy.ts
  server/src/apis/point/point.controller.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/ranking/ranking.module.ts
  server/src/apis/users/dto/create-sns-user.dto.ts
  server/src/apis/users/entities/user.entity.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.module.ts
  server/src/apis/users/users.service.ts
  server/src/app.module.ts
  server/src/common/common.module.ts
  server/src/common/config/typeorm.config.ts
  server/src/common/decorators/current-user.decorator.ts
  server/src/common/decorators/transactional.decorator.ts
  server/src/common/interceptors/auth-token.interceptor.ts
  server/src/common/level-calculator/level-calculator.module.ts
  server/src/common/logger/winston-logger.module.ts
  server/src/common/middleware/transaction.middleware.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.provider.ts
  server/src/common/utils/compare-value.util.ts
  server/src/common/utils/constants.util.ts
  server/src/common/utils/encrypt-value.util.ts
  server/src/common/utils/transaction-manager.util.ts
Labels: ✨ Feat, 🔨 Refactor, 📱BE

#185 [BE] 랭킹 조회 기능 수정 완료
  server/src/apis/ranking/dto/user-info-with-rank.dto.ts
  server/src/apis/ranking/dto/user-ranking.dto.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/users.service.ts
Labels: 🐞 BugFix, 📱BE

#189 [BE] TypeORM 마이그레이션 설정 및 User 테이블 마이그레이션 파일 생성 완료
  server/package.json
  server/src/app.module.ts
  server/src/configs/datasource.config.ts
  server/src/configs/typeorm.config.ts
  server/src/core/core.module.ts
  server/src/migrations/1718647700144-create-user-table.ts
  server/tsconfig.json
Labels: 🔨 Refactor, 📱BE

#190 [BE] repository pattern 적용하기
  server/src/core/core.module.ts
  server/src/core/database/generic/generic.repository.ts
  server/src/core/database/generic/root.entity.ts
  server/src/core/database/typeorm/generic-typeorm.repository.ts
  server/src/core/database/typeorm/transaction-manager.ts
  server/src/core/database/typeorm/typeorm.module.ts
  server/src/modules/user/user.service.ts
Labels: 🔨 Refactor, 📱BE

#191 [BE] Custom User Repository 생성 완료
  server/src/core/database/typeorm/base-time.entity.ts
  server/src/core/database/typeorm/generic-typeorm.repository.ts
  server/src/entities/user/user-repository.interface.ts
  server/src/entities/user/user-repository.module.ts
  server/src/entities/user/user.entity.ts
  server/src/entities/user/user.repository.ts
Labels: 🔨 Refactor, 📱BE

#192 [BE] User 엔티티에 객체 생성 메서드 구현
  server/src/entities/user/user.entity.ts
Labels: 📱BE

#193 [BE] UserInfo 엔티티 및 커스텀 레포지토리 추가 완료
  server/src/common/dto/ranking/user-info-with-rank.dto.ts
  server/src/core/database/typeorm/generic-typeorm.repository.ts
  server/src/entities/user-info/user-info-repository.interface.ts
  server/src/entities/user-info/user-info.entity.ts
  server/src/entities/user-info/user-info.module.ts
  server/src/entities/user-info/user-info.repository.ts
  server/src/modules/user/user.service.ts
Labels: 🔨 Refactor, 📱BE

#194 [BE] ProfilePhoto 엔티티 수정 및 커스템 레포지토리 추가 완료
  server/src/common/dto/user/profile-photo.dto.ts
  server/src/common/dto/user/user-profile.dto.ts
  server/src/entities/profile-photo/profile-photo-repository.interface.ts
  server/src/entities/profile-photo/profile-photo-repository.module.ts
  server/src/entities/profile-photo/profile-photo.entity.ts
  server/src/entities/profile-photo/profile-photo.repository.ts
  server/src/entities/user/user.repository.ts
  server/src/modules/user/user.service.ts
Labels: 🔨 Refactor, 📱BE

#188 [FE] 토큰값 전송형태 변경에 따른 수정
  client/src/utils/tokenUtils.ts
Labels: 🖥️FE

#195 [BE] 퀘스트 엔티티 수정 및 레포지토리 추가 완료
  server/src/core/database/generic/generic.repository.ts
  server/src/core/database/typeorm/generic-typeorm.repository.ts
  server/src/entities/quest/quest-repository.interface.ts
  server/src/entities/quest/quest-repository.module.ts
  server/src/entities/quest/quest.entity.ts
  server/src/entities/quest/quest.repository.ts
Labels: 🔨 Refactor, 📱BE

#197 [FE] 시맨틱 태그로 리팩토링
  client/src/components/ranking/RankingCard.tsx
  client/src/pages/Main.tsx
  client/src/pages/Ranking.tsx
  client/src/styles/globalstyles.ts
Labels: 🔨 Refactor, 🖥️FE
