Repository ingame-app/ingame, pull requests merged in 2024-04, with the labels that each got.

#3 [FE] 프론트엔드 초기 세팅 완료
  client/.gitignore
  client/.prettierrc
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/src/setupTests.ts
  client/tsconfig.json
Labels: Conf, FE, ⚙️ 환경설정

#12 [BE] 백엔드 환경 설정 완료
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/config/typeorm.config.ts
  server/src/main.ts
Labels: 📱BE, ⚙️ conf

#14 [BE] 엔티티 생성 완료
  server/src/apis/profilephoto.entity.ts
  server/src/apis/quest.entity.ts
  server/src/apis/sidequest.entity.ts
  server/src/apis/user.entity.ts
  server/src/apis/userinfo.entity.ts
Labels: ✨ Feat, 📱BE

#15 [FE] 프론트엔드 Global Style, MSW, axios 설정
  client/.gitignore
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/App.css
  client/src/App.tsx
  client/src/api/auth.ts
  client/src/assets/fonts/Pretendard-Black.woff
  client/src/assets/fonts/Pretendard-Bold.woff
  client/src/assets/fonts/Pretendard-ExtraBold.woff
  client/src/assets/fonts/Pretendard-ExtraLight.woff
  client/src/assets/fonts/Pretendard-Light.woff
  client/src/assets/fonts/Pretendard-Medium.woff
  client/src/assets/fonts/Pretendard-Regular.woff
  client/src/assets/fonts/Pretendard-SemiBold.woff
  client/src/assets/fonts/Pretendard-Thin.woff
  client/src/components/Title.tsx
  client/src/constant/api.ts
  client/src/index.css
  client/src/index.tsx
  client/src/layout/Layout.tsx
  client/src/logo.svg
  client/src/mocks/auth.ts
  client/src/mocks/browser.ts
  client/src/styles/globalstyles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/axios.ts
  client/tsconfig.json
  client/tsconfig.paths.json
Labels: 🖥️FE

#21 [BE] 폴더 구조 생성 완료
  server/package-lock.json
  server/package.json
  server/src/apis/auth/auth.controller.spec.ts
  server/src/apis/auth/auth.controller.ts
  server/src/apis/auth/auth.module.ts
  server/src/apis/auth/auth.service.spec.ts
  server/src/apis/auth/auth.service.ts
  server/src/apis/auth/dto/create-auth.dto.ts
  server/src/apis/auth/dto/update-auth.dto.ts
  server/src/apis/quests/dto/create-quest.dto.ts
  server/src/apis/quests/dto/update-quest.dto.ts
  server/src/apis/quests/entities/quest.entity.ts
  server/src/apis/quests/entities/side-quest.entity.ts
  server/src/apis/quests/quests.controller.spec.ts
  server/src/apis/quests/quests.controller.ts
  server/src/apis/quests/quests.module.ts
  server/src/apis/quests/quests.service.spec.ts
  server/src/apis/quests/quests.service.ts
  server/src/apis/ranking/dto/create-ranking.dto.ts
  server/src/apis/ranking/dto/update-ranking.dto.ts
  server/src/apis/ranking/ranking.controller.spec.ts
  server/src/apis/ranking/ranking.controller.ts
  server/src/apis/ranking/ranking.module.ts
  server/src/apis/ranking/ranking.service.spec.ts
  server/src/apis/ranking/ranking.service.ts
  server/src/apis/users/dto/create-user.dto.ts
  server/src/apis/users/dto/update-user.dto.ts
  server/src/apis/users/entities/profile-photo.entity.ts
  server/src/apis/users/entities/user-info.entity.ts
  server/src/apis/users/entities/user.entity.ts
  server/src/apis/users/users.controller.spec.ts
  server/src/apis/users/users.controller.ts
  server/src/apis/users/users.module.ts
  server/src/apis/users/users.service.spec.ts
  server/src/apis/users/users.service.ts
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
Labels: 📱BE, ⚙️ conf

#22 [FE] 프론트엔드 Redux 초기 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/counter.tsx
  client/src/store/counterSlice.ts
  client/src/store/index.ts
Labels: 🖥️FE, ⚙️ conf

#24 [FE] 프론트엔드 Route설정 및 각 페이지 생성
  client/src/App.tsx
  client/src/constant/route.ts
  client/src/pages/Error.tsx
  client/src/pages/Login.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Ranking.tsx
  client/src/pages/SignUp.tsx
  client/src/routes/routing.tsx
Labels: ✨ Feat, 🖥️FE
